#!/usr/bin/env bash

# Name: Liang Kooi Yap
# ID: 24332936
# Last modified: 23 May 2026

# How to run the script: ./analyse trending_videos_clean.csv

# Summary:

# Declare variable for input file
inputFile="$1"

# Error check 1: No input file specified
if [[ $# -eq 0 || -z "$inputFile" ]]
then
    echo "ERROR: No input CSV file provided" > /dev/stderr
    exit 1
fi

# Error check 2: Input file not found






