#!/usr/bin/env bash

# Name: Liang Kooi Yap
# ID: 24332936
# Last modified: 23 May 2026

# How to run the script: ./analyse trending_videos_clean.csv

# Summary:

# Declare variable for input file
inputFile="$1"

# Error check 1: No input file specified
if [[ $# -eq 0 || -z "$inputFile" ]]
then
    echo "ERROR: No input CSV file provided" > /dev/stderr
    exit 1
fi

# Error check 2: Input file not found
if [[ ! -f "$inputFile" ]]
then
    echo "ERROR: Input file not found in the current directory" > /dev/stderr
    exit 2
fi

# Error check 3: Input file is not CSV
if [[ "$inputFile" != *.csv ]]
then
    echo "ERROR: Input file expected in a CSV format" > /dev/stderr
    exit 3
fi

# Error check 4: Empty file
if [[ ! -s "$inputFile" ]]
then
    echo "ERROR: Empty file provided" > /dev/stderr
    exit 4
fi

# Following code section is for data analysis
gawk -F ',' '
    
# Start reading data after header and declare variable
NR > 1 {
    videoID = $1
    publishDate = $2
    views = $3
    likes = $4
    dislikes = $5
}


BEGIN {maxCount=0}
{
    # Count video occurrences and find max number of occurrences
    countVid[videoID]++
    if (countVid[videoID]>maxCount){
        maxCount = countVid[videoID]
    }

}

END{
    # Print the video ID that match max occurrences
    for (vid in countVid){
        if (countVid[vid] == maxCount){
            print "Most frequent video, ID: " vid
        }
    }
}

' "$inputFile" 





