#!/usr/bin/env bash


# Name: Liang Kooi Yap
# ID: 24332936
# Last modified: 22 May 2026

# How to run the script:

# Summary:


# Declare variable
inputFile="$1"

# Error check 1: Prompt error if no input file specified or user provide empty string
if [[ $# -eq 0 || -z "$inputFile" ]]
then
    echo "ERROR: No input CSV file provided" > /dev/stderr
    exit 1
fi

# Error check 2: Prompt error if input file not found in the current directory
if [[ ! -f "$inputFile" ]]
then
    echo "ERROR: Input file not found in the current directory" > /dev/stderr
    exit 2
fi

# Error check 3: Prompt error if input file is not a CSV file
if [[ "$inputFile" != *.csv ]]
then
    echo "ERROR: Input file expected in a CSV format" > /dev/stderr
    exit 3
fi

# Error check 4: Prompt error if input file is empty.
if [[ ! -s "$inputFile" ]]
then
    echo "ERROR: Empty file provided" > /dev/stderr
    exit 4
fi

# Error check 5: Prompt error if input CSV file has incorrect number of columns
# Find number of columns from header
numCols=$(head -n 1 "$inputFile" | gawk -F ',' '{print NF}')

# Prompt error message when if number of columns not equal to 7
if [[ "$numCols" -ne 7 ]]
then
    echo "ERROR: Expected 7 columns in the input" > /dev/stderr
    exit 5
fi

# Data cleaning processes
# 1. Exclude 'ratings_disabled' column and preserve first 5 columns 
gawk -F',' '{print $1 "," $2 "," $3 "," $4 "," $5 "," $6}' "$inputFile" > temp1

# 2. Delete rows that contain any empty field, even if they match number of field in the header
gawk -F',' '

# Keep the header from first row
NR == 1 {
    print $0 
}

# Process data from second row onwards
NR > 1 {

    keepRow = 1

    # If number of field is not 6, delete the row
    if (NF != 6){
        keepRow = 0
    }

    # Delete the row if any field in the current row is empty
    for (i=1; i <= NF; i++){
        if ($i == ""){
            keepRow = 0
        }
    }
    
    # Print the current row if the row has 6 fields and none of the field is empty
    if (keepRow == 1){
        print $0
    }
}' temp1 > temp2

# 3. Delete rows which contain 0 likes or dislikes
gawk -F ',' '

# Keep the header from first row
NR == 1 {
    print $0
}

# Process data from second row onwards. Keep rows if both likes and dislikes are not 0
NR > 1{
    if ($4!=0 && $5!=0){
        print $0
    }
}' temp2 > temp3





