#!/usr/bin/env bash

# Name: Liang Kooi Yap
# ID: 24332936
# Last modified: 22 May 2026

# How to run the script: ./clean trending_videos_unclean.csv

# Summary:
# The script is to clean the trending_videos_unclean.csv by removing the redundant column, trim datetime field into date field, delete rows that contain empty string


# Declare variable
inputFile="$1"

# Error check 1: Prompt error if no input file specified or user provide empty string
if [[ $# -eq 0 || -z "$inputFile" ]]
then
    echo "ERROR: No input CSV file provided" > /dev/stderr
    exit 1
fi

# Error check 2: Prompt error if input file not found in the current directory
if [[ ! -f "$inputFile" ]]
then
    echo "ERROR: Input file not found in the current directory" > /dev/stderr
    exit 2
fi

# Error check 3: Prompt error if input file is not a CSV file
if [[ "$inputFile" != *.csv ]]
then
    echo "ERROR: Input file expected in a CSV format" > /dev/stderr
    exit 3
fi

# Error check 4: Prompt error if input file is empty.
if [[ ! -s "$inputFile" ]]
then
    echo "ERROR: Empty file provided" > /dev/stderr
    exit 4
fi

# Error check 5: Prompt error if input CSV file has incorrect number of columns
# Find number of columns from header
numCols=$(head -n 1 "$inputFile" | gawk -F ',' '{print NF}')

# Prompt error message when if number of columns not equal to 7
if [[ "$numCols" -ne 7 ]]
then
    echo "ERROR: Expected 7 columns in the input" > /dev/stderr
    exit 5
fi

# Data cleaning processes
# 1. Exclude 'ratings_disabled' column and preserve first 6 columns. Also, standardised comments_disabled col to match the csv provided. trending_videos_clean.csv provided "True/False" under comments_disabled while Unclean csv is in "TRUE/FALSE" format.
gawk -F',' '
NR == 1 {
    print $1 "," $2 "," $3 "," $4 "," $5 "," $6
}

NR > 1 {
    # Convert all values in col 6 to lower, then standardise the value to match the csv file provided
    if (tolower($6) == "true"){
        $6 = "True"
    }
    else if (tolower($6) == "false"){
        $6 = "False"
    } 
    print $1 "," $2 "," $3 "," $4 "," $5 "," $6
}' "$inputFile" > temp1

# 2. Delete rows that contain any empty field, even if they match number of field in the header
gawk -F',' '

# Keep the header from first row
NR == 1 {
    print $0 
}

# Process data from second row onwards
NR > 1 {

    keepRow = 1

    # If number of field is not 6, delete the row
    if (NF != 6){
        keepRow = 0
    }

    # Delete the row if any field in the current row is empty
    for (i=1; i <= NF; i++){
        if ($i == ""){
            keepRow = 0
        }
    }
    
    # Print the current row if the row has 6 fields and none of the field is empty
    if (keepRow == 1){
        print $0
    }
}' temp1 > temp2

# 3. Remove duplicates rows in the dataset
gawk '

# Keep the header from first row
NR == 1{
    print $0
}

# Process data from second row
# If current row is unique, keep the row
NR > 1 {
    if (!UniqCurrentRow[$0]){
        UniqCurrentRow[$0] = 1
        print $0
    }
}' temp2 > temp3

# 4. Delete rows which contain 0 likes or dislikes
gawk -F ',' '

# Keep the header from first row
NR == 1 {
    print $0
}

# Process data from second row onwards. Keep rows if both likes and dislikes are not 0
NR > 1{
    if ($4!=0 && $5!=0){
        print $0
    }
}' temp3 > temp4

# 5. Remove time data from publish_date column
gawk -F ',' '

# Keep the header from first row
NR == 1 {
    print $0
}

# Remove the time from the date (column 2) by replacing anything from "T." with empty string
NR > 1 {
    sub(/T.*/,"",$2)
    print $1 "," $2 "," $3 "," $4 "," $5 "," $6 
}' temp4 > trend_videos_manual.csv




