#!/usr/bin/env bash

# Name: Liang Kooi Yap
# ID: 24332936
# Completion Date: 24 May 2026

# How to run the script: ./analyse trending_videos_clean.csv

# Summary:
# 1. The script first check the same error checking in task 1
# 2. The script provides data analysis on finding most occurrence videos, calculate the mean number of views, finding videos that has/have maximum dislikes, calculate and finding highest engagement rate with formula (likes+dislikes)/views, and calculate and finding least net setiment rate with formula (likes-dislikes)/views. 
# 3. If there is a tie between 2 or more videos, they will be presented in a clear and sensible format

# Assumptions to complete task 2:
# 1. Since records with 0 likes or dislikes are removed, it indicates at least 1 like or dislike for each record. Hence, there must be at least 1 view in the dataset. So, division by zero error on calculating engagement rate and net sentiment rate can be ommitted.

# Declare variable for input file
inputFile="$1"

# Error check 1: No input file specified
if [[ $# -eq 0 || -z "$inputFile" ]]
then
    echo "ERROR: No input CSV file provided" > /dev/stderr
    exit 1
fi

# Error check 2: Input file not found
if [[ ! -f "$inputFile" ]]
then
    echo "ERROR: Input file not found in the current directory" > /dev/stderr
    exit 2
fi

# Error check 3: Input file is not CSV
if [[ "$inputFile" != *.csv ]]
then
    echo "ERROR: Input file expected in a CSV format" > /dev/stderr
    exit 3
fi

# Error check 4: Empty file
if [[ ! -s "$inputFile" ]]
then
    echo "ERROR: Empty file provided" > /dev/stderr
    exit 4
fi

# Following code section is for data analysis
gawk -F ',' '
    
# Start reading data after header and declare variable
NR > 1 {
    videoID = $1
    publishDate = $2
    views = $3
    likes = $4
    dislikes = $5
    
    # Q1. Calculate max occurrence of video
    countVid[videoID]++

    if (countVid[videoID] > maxCountVid){
        maxCountVid = countVid[videoID]
    }

    # Q2. Sum views and count num of records to find mean of views
    totalViews += views
    countRecords++

    # Q3. Find the maximum dislikes in the data
    if (countRecords == 1 || dislikes > maxDislikes){
        maxDislikes = dislikes
    }
    # Store the video ID and dislikes for each row
    rowDislikes[countRecords] = dislikes
    rowVideoID[countRecords] = videoID
    
    # Q4. Calculate engagement rate and find its highest
    engageRate = (likes + dislikes) / views

    # Find the highest engagement rate
    if (countRecords == 1 || engageRate > maxEngageRate){
        maxEngageRate = engageRate
    }
    
    # Store engagement rate and date for each row
    rowEngageRate[countRecords] = engageRate
    rowPubDate[countRecords] = publishDate

    # Q5. Calculate sentiment rate and find the least of its
    sentiRate = (likes - dislikes) / views

    # Find the least sentiment rate
    if (countRecords == 1 || sentiRate < minSentiRate){
        minSentiRate = sentiRate
    }

    # Store the sentiment rate for each row
    rowSentiRate[countRecords] = sentiRate
}

END{
    # Q1. Print the video ID that match max occurrences
    mostFreqVid = ""
    
    # Append video ID is same frequency and print video ID
    for (vid in countVid){
        if (countVid[vid] == maxCountVid){
            if (mostFreqVid == ""){
                mostFreqVid = vid
            }
            else{
                mostFreqVid = mostFreqVid "," vid 
            } 
        }
    }
    print "Most frequent video, ID: " mostFreqVid
    
    # Q2. Print the mean of views using printf function
    printf "Mean number of views: %.2f\n", totalViews / countRecords

    # Q3. Print the max dislikes
    maxDislikeVid = ""

    for (i = 1; i<=countRecords;i++){
        if (rowDislikes[i] == maxDislikes){
            if (maxDislikeVid == ""){
                maxDislikeVid = rowVideoID[i]
            }
            else{
                maxDislikeVid = maxDislikeVid "," rowVideoID[i]
            }
        }
    }
    print "Max dislikes video, ID: " maxDislikeVid

    # Q4. Print the vid ID and date with highest engagement
    highestEngageVid = ""

    for (i=1; i <= countRecords; i++){
        if (rowEngageRate[i] == maxEngageRate){
            result = rowVideoID[i] ", dated: " rowPubDate[i]

            if (highestEngageVid == ""){
                highestEngageVid = result
            }
            else{
                highestEngageVid = highestEngageVid "; " result
            }
        }
    }

    print "Highest engagement rate video, ID: " highestEngageVid
    
    # Q5. Print the vid ID and date with least sentiment rate
    minSentiVid = ""

    for (i=1;i<=countRecords;i++){
        if(rowSentiRate[i] == minSentiRate){
            result = rowVideoID[i] ", dated: " rowPubDate[i]

            if (minSentiVid == ""){
                minSentiVid = result
            }
            else{
                minSentiVid = minSentiVid "; " result
            }
        }
    }
    print "Least sentiment rate video, ID: " minSentiVid
}

' "$inputFile" 





